@echo off
setlocal

chdir /d D:\project

set PIPELINE_CRAWL_BATCH_SIZE=20
set PIPELINE_SPOTIFY_RPS=3.0
set PIPELINE_PLAYLIST_DELAY_MIN=0.1
set PIPELINE_PLAYLIST_DELAY_MAX=0.3
set PIPELINE_PER_LABEL_LIMIT=25
set PIPELINE_TOTAL_LIMIT=400
set PIPELINE_AUDIO_DURATION=20
set PIPELINE_MIN_AUDIO_DURATION=12
set PIPELINE_MIN_AUDIO_SIZE_BYTES=180000
set PIPELINE_MIN_TRAIN_SAMPLES=64
set PIPELINE_MIN_LABEL_COVERAGE=8

call run_full_cnn_pipeline.bat
exit /b %ERRORLEVEL%
